name: Auto-Reboot Streamlit App

on:
  schedule:
    - cron: '0 0,12 * * *'  # Corre cada 12 horas (a la medianoche y a mediodía UTC)
  workflow_dispatch: 

jobs:
  reiniciar-app:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Hacer un commit vacío y empujar
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "🤖 Auto-reboot: Reinicio diario a las 6am"
          git push
